# Generated by Django 3.2.15 on 2022-10-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importproduct', '0002_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user',
            field=models.IntegerField(),
        ),
    ]
