# Generated by Django 3.2.15 on 2022-10-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importproduct', '0003_alter_billing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='charge_id',
            field=models.TextField(max_length=200, null=True, unique=True),
        ),
    ]
