# Generated by Django 3.2.15 on 2022-10-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importproduct', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
