# Generated by Django 3.2.15 on 2022-10-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20221024_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authappshopuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authappshopuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='authappshopuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='authappshopuser',
            name='user_permissions',
        ),
    ]
